version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
    ports:
      - "5432:5432"