server:
  port: 8090

cloud:
  db-host: localhost
  currency-url: http://localhost:8080

service:
  currency:
    url: ${cloud.currency-url}

spring:
  application:
    name: processing-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    username: postgres
    password: masterkey
  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    user: postgres
    password: masterkey

logging:
  level:
    org.springframework.cloud.gateway: DEBUG